apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-service
  # labels:
  #   environment: production

spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http-port
      port: 80 # service port
      targetPort: 80 # conatiner port
      nodePort: 31233 # NodePort port
